
name: Publish Docker image

on:   
  push:
    branches:   
      - 'main'
    tags:       
      - '*'

jobs:  

  push_to_registry:  
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:  
      - name: Check out the repo
        uses: actions/checkout@v2   

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/xycode-kerman/asmre_backend:${{github.sha}}